[package]
name = "rust_bench"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rust_bench"
path = "./src/main.rs"

[dependencies]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
